name: substrate_codec
version: 0.1.0
publish_to: none

dependencies:
  bs58: ^1.0.1
  convert: ^2.1.1
  cryptography: ^1.4.1
  pointycastle: ^1.0.1
  quiver: ^2.1.5

dev_dependencies:
  test: ^1.16.5

environment:
  sdk: ">=1.19.0 <3.0.0"