name: substrate_codec
version: 0.1.0
publish_to: none

dependencies:
  bs58: ^1.0.2
  convert: ^3.0.0
  cryptography: ^2.0.0
  pointycastle: ^3.6.2
  quiver: ^3.1.0
  http: ^0.13.1
  # sync_http: ^0.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"