name: substrate_codec
version: 0.1.0
publish_to: none

dependencies:
  bs58: ^1.0.1
  convert: ^2.1.1
  cryptography: ^1.4.1
  scalecodec:
    git:
     url: https://github.com/nbltrust/dart-scale-codec
     ref: '0.1.2'

environment:
  sdk: ">=1.19.0 <3.0.0"